---
title: "Paper Outline"
format:
    html:
      self-contained: true
    pdf:
      keep-tex: true

bibliography: ../references.bib
---



# Introduction

1. Characterization of Inland Water Bodies via Remote Sensing is Challenging
   - complex spectral signatures
   - limited spatial and temporal resolution (long satellite overpasses)
   - nevertheless remote sensing has significant potential
   - Harmful Algal Bloom (HAB) classification and mapping
   - Oil Spill mapping

2. Hyperspectral Imaging addresses spectral limitations of traditional remote sensing platforms

3. Supervised methods
   - Inversion of optically-active parameters
   - Key limitation: availability of in-situ reference data
     - Cite Aurin et al. and Ross et al. here
   - When ground truth data are limited, classification is an alternative approach, e.g. "bad" to "good" water quality

4. Unsupervised methods
   - Unsupervised classification & ML Techniques
   - Endmember Extraction and Spectral Unmixing

5. Robot Teams and HSI equipped Drones

6. This paper
   - Extend capabilities of robot team by showcasing capabilities for unsupervised classification
   - Utilize GTM as Bayesian extension of SOM to enable unsupervised classification
   - GTM also enables extraction of spectral features associated with each node
   - Two case studies
     1. GTM trained on water-only HSI data for lake
        - Identify interesting regions for further examination by robot team
        - Investigate spectral variability of water
     2. GTM on dataset combining grass and water pixels with a simulated pollution event using Rhodamine tracer dye
        - Use extracted GTM "endmembers" together with NS3 to map abundance
        - Identify abundance of algae
        - Map evolution of Rhodamine dye plume



# Materials and Methods

1. Data Collection
   - Describe collection at site in Montague, North Texas
2. Autonomous Robot Team
   - Describe drone
     - Alta X Quadcopter
     - Resonon Pika XC2 HSI
     - Intel Nuc compute
   - describe georectification procedure
3. Pre-Processing
4. Generative Topographic Mapping
  - Original SOM paper [@kohonen-som-1]
  - Heskes reinterpretation of SOM algorithm as stochastic gradient descent on an energy suface i.e. justification with a cost function [@som-cost-function]
  - GTM paper [@gtm-bishop-1]
    - Describe algorithm
    - Describe parameters
  - Bayesian Information Criterion and Akaike Information Criterion for Hyperparameter Optimization
    - A full Bayesian treatment would involve marginalization over all possible parameter values but this is much more computational efficient.
5. Abundance Mapping with the Normalized Spectral Similarity Score
   - Describe different metrics for comparison of spectra
     - Trade-off between metrics that distinguish changes in overall intensity and changes in  peak location, i.e. hue



# Results

1. Two Case Studies
2. GTM Fit on Full Dataset
3. Hyperparameter Optimization with BIC
4. Spectral Signature Identification
5. Water Class Map (Water Only GTM)
6. Algae Identification
7. Dye Plume Identification

# Discussion

1. GTM Applications in our Paper
2. Comparison to existing approaches
   - Unsupervised Classification
   - Endmember Extraction & Spectral Unmixing
   - Applications for either of these with Drones?
3. Use of GTM and Unsupervised methods for Robot Team
   - As a feature transformer/preprocessor for supervised methods (as opposed to, say, PCA or k-NN)
   - identification of "interesting" regions for intelligent deployment of robotic boat
     - don't continue collecting data in region that is similar
     - provision boat to maximize data collection across distribution of GTM classes
 4. Extensions and future work
    - Incorporation of GTM extensions for efficient online-learning
      - Currently GTM classes can quickly be applied (in real time) once they are trained to generate abundance maps e.g. chlorophyll, algae, etc...
      - Key limitation of GTM is similar to SOM and k-NN: you need to compute distances between samples and latent nodes. This can scale poorly for very large datasets
      - Bishop suggests a way to augment GTM training algorithm to enable online training of GTM. This could be deployed on-board the UAV to perform classification and identify spectral signatures in near-real time.
      - Extensions of GTM [@gtm-bishop-2]
    - Utilize the GTM with in-situ data collection to identify spectral signatures of specific algal species 


# Conclusions


# NOTES AND CITATIONS

1. Applications of remote sensing to water quality
   - machine learning (XGBoost) used with paired remote sensing imagery and in-situ data to classify imagery into 5 categories including 3 for harmful algal blooms [@ghatkar2019classification]
   - Spectral signatures of classes are complex and often overlapping [@thenkabail2018hyperspectral]
   - Remote sensing used for oil spill analysis: extent and thickness mapping [@kokaly2013spectroscopic; @leifer2012state]
   - Sun glitter remains a key challenge for sensing in the visible portion of the spectrum but multi and hyperspectral imagers have been used for oil spill identification and to identify their impacts on vegetation stress and mortality [@fingas2014review; @khan2018modern]

2. Hyperspectral Imagery
   - applications include food quality & safety, medical diagnoses, precision agriculture, and forensic document examination [@khan2018modern]
   - Hyperspectral data were used to distinguish oils by type, e.g. crude, diesel, gasoline, and palm [@yang2020characterization]

3. Supervised regression and classification for water quality
   - common approach is inversion of optically-active water quality parameters such as chlorophyll-a, blue-green algae, turbidity, and temperature [@ritchie2003remote]
   - Combining spectral indices such as the NDVI together with machine learning is a popular approach [@thenkabail2018hyperspectral; @sagan2020monitoring; @lu2021retrieval]
   - Polynomial regression models for chlorophyll-a, turbidity [@zhang2022selection]
   - Key limitation is collection of sufficient quantity of in-situ reference data
   - Ross et al. created a comprehensive dataset with over 600,000 water quality records matching optically active water quality parameters with associated satellite imagery from Landsat 5,7,8. To achieve this quantity of data, they needed records spanning 1984 to 2019 [@ross2019aquasat]
   - Aurin et al. took a similar route combining 30 years of remote sensing imagery with in-situ data from over 500 field compaigns for CDOM, organic carbon, etc... [@aurin2018remote].
   - When ground truth data aren't available in sufficient quantity, classification into water quality categories is another approach (ground truth can be easier to obtain by expert analysis of scene) [@koponen2002lake]

- When no ground-truth data are available, unsupervised classification can still help partition imagery into groups or clusters.
   - Many data-driven, ML methods have been employed for the task including various matrix factorizations, k-nearest neighbors, fuzzy c-means, density estimation methods, etc. [@zhang2019hyperspectral]
   - Additionally unsupervised approaches can be used to perform nonlinear dimensionality reduction & pre-processing for supervised approaches.
   - SOM used for remote sensing imagery classification [@msom-remote-sensing]
   - SOM used for clustering and data compression of HSI cube-sat [@danielsen2021self]
   - SOM used for land-use and land-cover change analysis [@penfound2021analysis]

4. Endmember Extraction and Spectral Unmixing
   - This is a related problem where the goal is to identify unique spectral signatures which combine (linearly or non-linearly) to produce the measured signal.
   - Having identified the set of endmembers, we then seek to determine their relative abundance in each pixel
   - Many statistical approaches for extracting endmembers [@berman2004ice]
   - Sparse PCA used for endmember extraction [@yousefi2016mineral]
   - Popular spectral unmixing approach is to treat "pure" endmembers as vertices of a simplex [@plaza2012endmember; @nascimento2005vertex]
   - Convolutional Neural Networks with Autoencoder architectures are a popular ML approach which identify endmembers and perform non-linear unmixing [@palsson2020convolutional; @non-negative-autoencoders; @su2019daen; @borsoi2019deep]
   - Self Organizing Map is another approach which has been used for endmember extraction together with neural networks for abundance mapping (unmixing) [@cantero2004analysis]
   - SOM has bee nused for identifying synoptic-scale patterns in wind and sea surface temperature data [@som-satellite]
   - SOM used for HSI feature extraction [@som-hsi]
   - drawback of autoencoder and other statistical approach is lack of a (topological) relationship between the classes/endmembers. Is endmember 1 closer to endmember 2 or endmember 10? The SOM addresses this. The GTM is even better...

5. Abundance Mapping
   - Many different spectral similarity functions exist for comparing spectra. Each have trade-offs between ability to distinguish differences in intensity versus differences in peak location (hue) [@deborah2015comprehensive]
   - spectral angle mapper is popular similarity function used in endmember extraction. The SAM is nice because it is more sensitive to shape than scale [@jiang2020classification]
   - spectral correlation mapper introduced to as a statistical alternative to SAM based on covariance instead of spectral angle [@de2000spectral]
   - Normalized spectral similarity score developed by Nidamanuri et al. combine the mean-squared error with spectral angle for a happy medium [@nidamanuri2010normalized]

6. Drone-based HSI
   - Near-earth HSI addresses spatial, spectral, and temporal limitations of satellite and airborne platforms. UAV-based HSI enable fine-scale mapping [@banerjee2020uav]
   - Drones can be equipped with HSI and compute to enable rapid generation of spectral indices like the NDVI for applications such as precision agriculture [@horstrand2019uav]
   - UAV-based HSI can be georectified to centimeter-scales without need for ground control points by using on-board GPS and IMU [@arroyo2019implementation]
   - UAV-based HSI for turbidity estimation [@vogt2016near]


